---
apiVersion: v1
kind: Service
metadata:
  name: glance-k8s
  namespace: glance
  annotations:
    metallb.universe.tf/address-pool: k8s-vlan-pool
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.20.61"
  selector:
    app: glance-k8s
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
