---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: corpocache
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/csGIT34/CorpoCache.git
    targetRevision: main
    path: helm/corpocache
    helm:
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: corpocache
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        linkerd.io/inject: enabled
    syncOptions:
      - CreateNamespace=true
