---
apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: pve-exporter
  ports:
    - name: metrics
      port: 9221
      targetPort: 9221
      protocol: TCP
