---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure services (service mesh, ingress, monitoring)
  sourceRepos:
    - https://github.com/csGIT34/homelab.git
    - https://helm.linkerd.io/edge
    - https://argoproj.github.io/argo-helm
    - https://metallb.github.io/metallb
    - https://coredns.github.io/helm
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
    - namespace: linkerd-viz
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: coredns
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
