---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: jellyfin
    name: jellyfin-media
  nfs:
    server: 10.0.10.11
    path: /mnt/media
    readOnly: true
