---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
  labels:
    app: pgadmin
type: Opaque
stringData:
  default-email: admin@home.lab
  default-password: pgadmin-homelab
