---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/csGIT34/homelab.git
    targetRevision: main
    path: kubernetes/manifests/wireguard/
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
