---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app: unpoller
spec:
  type: ClusterIP
  selector:
    app: unpoller
  ports:
    - name: metrics
      port: 9130
      targetPort: 9130
      protocol: TCP
