---
# ArgoCD
argocd_namespace: argocd
argocd_chart_version: "9.4.1"
argocd_chart_repo: https://argoproj.github.io/argo-helm
argocd_nodeport: 30443

# Linkerd
linkerd_namespace: linkerd
linkerd_viz_namespace: linkerd-viz

# Git repo for ArgoCD
argocd_repo_url: https://github.com/csGIT34/homelab.git
argocd_repo_branch: main

# Kubeconfig
kubeconfig_path: "{{ playbook_dir }}/../kubeconfig"
