---
- name: Reboot for NVIDIA driver
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Restart Ollama
  ansible.builtin.systemd:
    name: ollama
    state: restarted
    daemon_reload: true
