---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: duckdns-update
  namespace: teamspeak
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: duckdns
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - 'curl -s "https://www.duckdns.org/update?domains=$(DUCKDNS_DOMAIN)&token=$(DUCKDNS_TOKEN)&ip="'
              env:
                - name: DUCKDNS_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: duckdns-token
                      key: domain
                - name: DUCKDNS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: duckdns-token
                      key: token
          restartPolicy: OnFailure
