---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-ui
  namespace: wireguard
spec:
  type: ClusterIP
  selector:
    app: wg-easy
  ports:
    - name: http
      port: 51821
      targetPort: 51821
      protocol: TCP
