---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy
  namespace: wireguard
  annotations:
    metallb.universe.tf/address-pool: k8s-vlan-pool
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.20.82"
  selector:
    app: wg-easy
  ports:
    - name: wireguard
      port: 443
      targetPort: 443
      protocol: UDP
