---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://helm.linkerd.io/edge
    chart: linkerd-viz
    targetRevision: "*"
    helm:
      valuesObject:
        dashboard:
          enforcedHostRegexp: ^(localhost|127\.0\.0\.1|linkerd\.homelab\.local|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$
        resources:
          cpu:
            limit: 500m
            request: 100m
          memory:
            limit: 256Mi
            request: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
