---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://helm.linkerd.io/edge
    chart: linkerd-control-plane
    targetRevision: "*"
    helm:
      valuesObject:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjzCCATSgAwIBAgIRAISd0XE4LVFMcRWWnanyf5EwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYwMjA4MjMz
          NDU4WhcNMzYwMjA2MjMzNDU4WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDi1L2MDZ6gA6yKP
          yf5mu5AWni/cF4gIjtUzBoc/liHP9BV+4P4t/PEOW9ml1ZeaJcCfA29Emk/zVmnw
          Zi/lKeKjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBTmgeb63zyV8JBonLTKPqFd/Gfz2DAKBggqhkjOPQQDAgNJADBGAiEA
          vdd5kiELpWwts7iRBmyocl9hH+pviZUy/rts5QMcDVkCIQDOH4/StDiN5gHDm+V7
          ueXlVDmSl06ToRKP3+OZLDnfmw==
          -----END CERTIFICATE-----
        identity:
          issuer:
            scheme: kubernetes.io/tls
        resources:
          cpu:
            limit: 500m
            request: 100m
          memory:
            limit: 256Mi
            request: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
