---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  type: ClusterIP
  selector:
    app: speedtest-tracker
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
